language: node_js

node_js:
    - 9

    deploy:
    provider: npm
    email: admin@leflair.vn
    api_key: $NPM_AUTH_TOKEN
    on:
        branch: master
        tags: true

        notifications:
    email: false
