language: node_js
node_js:
    - 9
branches:
  only:
  - development
  - master
deploy:
    provider: npm
    email: admin@leflair.vn
    api_key: $NPM_AUTH_TOKEN
    skip_cleanup: true
    on:
        branch: master
        tags: true
notifications:
    email: false
